var text = {

	userAdjective: "awesome smelly cute happy silly depressed sad weepy eccentric pink black sassy purple screaming anxious rude funky green captain comrade professor imperator evil sinister dark smart doctor space galaxy flying".split(" "),
	userNoun: "pizza taco cat dog ferret poet goth sushi puppy kitten monkey pickle cheese lizard dinosaur hipster hippie wallaby chicken ghost alien zombie falafel wizard toaster fish".split(" "),
	userNumber: "42 69 666 314 99 85 626 360 001 007 123 321 222 514".split(" "),
	username: "#userAdjective##userNoun##userNumber#",

	caption: [
		"I'm here for a good time not a long time",
		"Where you movin'? I said, onto better things",
		"Know yourself, know your worth",
		"Make the most out of tonight, and worry ‘bout it all tomorrow",
		"I'm way up, I feel blessed",
		"I cannot see heaven being much better than this",
		"Live for today, plan for tomorrow, party tonight",
		"My excuse is that I'm young",
		"They ain't make me what I am, they just found me like this",
		"Last name ever, first name greatest",
		"On my worst behaviour",
		"Worrying about your followers, you need to get your dollars up",
		"Never not chasing a million things I want",
		"Weekend, please don't leave me.",
		"Don't let anyone tell you that you're not strong enough.",
		"Be who and what you want, period.",
		"Stay strong, the weekend is coming.",
		"Whatever you do in life, make sure it makes you happy.",
		"The question isn't can you, it's will you?",
		"What do you think of the view?",
		"When I feel a little down, I put on my favorite high heels and dance.",
		"Friday, my second favorite F word.",
		"I'll never try to fit in. I was born to STAND OUT.",
		"Never love anyone who treats you like you're ordinary.",
		"Trying to forget it but the memories are too strong.",
		"Truth is, I'm crazy for you. And everyone can see that but you.",
		"I act like I'm ok, but I'm really not.",
		"Stop looking for happiness in the same place you just lost it.",
		"Don't worry if you haven't found your true love, they're just with someone else right now.",
		"Never cry for that person who doesn't know the value of your tears.",
		"If I die tomorrow, will you remember me?",
		"Keep smiling because life is a beautiful thing and there's so much to smile about.",
		"Being single is smarter than being in the wrong relationship.",
		"YOLO",
		"Life changes like the weather.",
		"I hope you remember today is never too late to be brand new.",
		"They used to shout my name, now they whisper it.",
		"Life is not measured by the number of breaths you take, but the moments that take your breath away.",
		"Stay sharp and far from timid.",
		"These are the days we live for.",
		"Life is short, false; it's the longest thing you do.",
		"Work until your idols become your rivals.",
		"Some days start better than others.",
		"I need a six month holiday, twice a year.",
		"There may be no excuse for laziness, but I'm still looking.",
		"I'm your worst nightmare.",
		"Life goes on, with or without you.",
		"5'2 is my height but my attitude is 6'1",
		"Own what's yours, or else others will try to.",
		"You couldn't handle me even if I came with instructions.",
		"Forgive, yes. Forget, never.",
		"I don't need any part-time people in my life.",
		"All we have is NOW.",
		"We got that Friday feeling.",
		"Disappointed but not surprised.",
		"It is not how much we have, but how much we enjoy, that makes happiness.",
		"The most important thing is to enjoy your life – to be happy – it's all that matters.",
		"Life is not a problem to be solved, but a reality to be experienced.",
		"It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
		"Escape the ordinary.",
		"Always classy, never trashy, and a little bit sassy.",
		"I don't need your approval to be me.",
		"I am who I am, I am what I am, I do what I do and I ain't never gonna do it any different. I don't care who likes it and who don't.",
		"Take me as I am, or watch me as I go.",
		"Don't talk, just act. Don't say, just show. Don't promise, just prove.",
		"Never stop doing great just because someone doesn't give you credit.",
		"We are who we pretend to be.",
		"Adulting is overrated.",
		"In every life, a little rain must fall.",
		"I'm not messy, I'm just one of those creative types.",
		"Perfect day to be working from home!",
		"Sometimes life takes your breath away.",
		"On the shoulders of giants.",
		"Not all who wander are lost.",
		"This is an inspirational quote - Anonymous.",
		"Cleanliness is next to godliness but I'd rather be devilish." ,
		"It hurts to be this good.",
		"Dance like there's nobody watching. Love like you'll never be hurt. Sing like there's nobody listening. And live like it's heaven on earth."
	],

	hashtag: "blessed yolo idgaf love peace respect hashtag octothorpe instagood beautiful happy followme refreshinglyhonest honestcaption nofilter life amazing beauty instaglam photography lol swag party lifestyle home weekend awesome nice inspirational".split(" "),

	cat: "catsofinstaglam bestmeow adventurecat cats softkitty nyan furiends fourleggedfuriend catto tongueouttuesday caturday petsofinstaglam pussypower lolcat canhazcheezburger".split(" ")
}
